---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: build

  roles:
    - common
    - geerlingguy.java

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: build

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: build

  roles:
    - db

- name: deploy configurations
  hosts: all
  remote_user: build

  roles:
    - configs

- name: deploy puppet
  hosts: puppet
  remote_user: build

  roles:
    - geerlingguy.puppet
